sudo: required
language: python
python: '2.7'
cache: pip

install:
- openssl aes-256-cbc -K $encrypted_1b0fd0215972_key -iv $encrypted_1b0fd0215972_iv -in secret.zip.enc -out secret.zip -d
- unzip secret.zip

script:
- sudo cp deploy/21-prepare.conf /etc/rsyslog.d/
- sudo sed -i '/KLogPermitNonKernelFacility/\#KLogPermitNonKernelFacility' /etc/rsyslog.conf
- sudo sed -i '/\$PrivDropToUser syslog/\$PrivDropToUser adm' /etc/rsyslog.conf
- sudo sed -i '/xconsole/console' /etc/rsyslog.d/50-default.conf
- sudo service rsyslog restart
- sudo rsyslogd -version
- sudo rsyslogd -N1

- pip install -r requirements.txt
- behave features/mandatory.feature
- python provision.py input.yml
