sudo: required
language: python
python: '2.7'
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_1b0fd0215972_key -iv $encrypted_1b0fd0215972_iv
  -in secret.zip.enc -out secret.zip -d
- echo "..."
install:
- pip install -r requirements.txt
script:
- python lib/create_vultr_vm.py
