language: node_js
# travis runs 'npm install' and 'npm test'
node_js:
- '6'

cache:
  directories:
  - node_modules

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
- openssl aes-256-cbc -K $encrypted_1b0fd0215972_key -iv $encrypted_1b0fd0215972_iv
  -in secret.zip.enc -out secret.zip -d
- unzip secret.zip

script:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 key
  - ssh-add key
  - echo "Host 108.61.171.67" >> ~/.ssh/config
  - echo "IdentityFile /home/travis/build/nicosmaris/vm/key" >> ~/.ssh/config
  - echo "port 22" >> ~/.ssh/config
  - echo "user root" >> ~/.ssh/config
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  - npm run pwd
