language: node_js
# travis runs 'npm install' and 'npm test'
node_js:
- '6'

cache:
  directories:
  - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_1b0fd0215972_key -iv $encrypted_1b0fd0215972_iv
  -in secret.zip.enc -out secret.zip -d
- unzip secret.zip

script:
  - echo -e "Host 104.207.130.164\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm run pwd
