sudo: required

services:
- docker

before_install:
- ifconfig

script:
- python -m SimpleHTTPServer 8080 &
- sleep 1
- ifconfig eth0 | perl -n -e 'if (m/inet addr:([\d\.]+)/g) { print $1 }'
- ifconfig eth0 | perl -n -e 'if (m/inet addr:([\d\.]+)/g) { print $1 }' > ip
- bash deploy.sh

# the env var GH_TOKEN is used by deploy.sh
env:
  global:
    secure: mTAUAl44FZLA5TiOsVpw/91DhOWNxtY2DjjY2bnPgiQZ26NKn44HYFGqKUwvOunKcg9UKuthuvBuOoJTN/y7Q2No8oRovC/YjM16PIY1U4je9lexXfGtivvn7soAxbvKdLrCgbGhRDfo2wsO8DTsmvlAMoLjdXHqBHwRdoUlS5LACGk58EagTZhR6rYxHDrebqRgYLp9J3hdbM5KeJcCxZXUDkGsBx5zFokQWWxulvdZSycq5YMLjGA50rD4da0tMcQfOY+oUIyatGz35X0Us77xNn+4mbI6Baz6x7JEJHn3BejLTS1Pe9vd1mvXsgBU/VTlgZiTPjL5/yc40Jcq4u3hGyV49FMwg54AC+qXs0pT6Iom50+Wh3u+8+sYivaIpWhkp8COhlR/yudOSk5iI+D4FvpadPYauzyoSe0VUgEATmad34tYRGWTpOKSalcs+x9MvSqc3Ge+dFFzbBDd9IZluYBbs+ybjKH9Ii6+BRjounoWcLblNOkZ/jzT6N3hCj8CuKVEd94QV9ZRz4J7kY7SH0zpPWHtRm2xM8/NSSEzP2aZDHCEDShRWbMLqrpwxD/DJM6huA41mgQJq6YeCbMW4JDvPfwMAPaeAyp3hWVEfQObrrYL+NbVXCLBwbCk6gsw0Ich/waLD0K0c2csQjASfEPknjAQLGcqfO3CfOA=
