sudo: required
language: python
python: '2.7'
cache: pip

install:
- openssl aes-256-cbc -K $encrypted_1b0fd0215972_key -iv $encrypted_1b0fd0215972_iv -in secret.zip.enc -out secret.zip -d
- unzip secret.zip
- sudo bash configure-linux.sh -a nicosmaris -t $(cat loggly_token) -u nicos -p $(cat loggly_password)

script:
- exec 1> >(logger -s -t $(basename $0)) 2>&1
- sed -i "s/logglytoken/$(cat loggly_token)/" deploy/install_docker.sh
- sed -i "s/logglypassword/$(cat loggly_password)/" deploy/install_docker.sh
- pip install -r requirements.txt
- behave features/mandatory.feature
- python provision.py input.yml

