sudo: required
language: python
python: '2.7'
cache: pip

before_install:
- unzip secret.zip

install:
- pip install -r requirements.txt
- behave features/mandatory.feature

script:
- python provision.py input.yml
