sudo: required

services:
  - docker

before_install:
  - ifconfig

script:
  - python -m SimpleHTTPServer
  - sleep 1
  - ifconfig eth0 | perl -n -e 'if (m/inet addr:([\d\.]+)/g) { print $1 }'
  - ifconfig eth0 | perl -n -e 'if (m/inet addr:([\d\.]+)/g) { print $1 }' > ip
  - bash deploy.sh
#  - docker run --name db --net=host -p 0.0.0.0:9042:9042 -p 0.0.0.0:9160:9160 -e "CASSANDRA_LISTEN_ADDRESS=127.0.0.1" -e "MAX_HEAP_SIZE=128M" -e "HEAP_NEWSIZE=24M" -d cassandra:2.0 >> /tmp/cassandra.log 2>&1

