sudo: required
language: python
python: '2.7'
cache: pip

install:
- openssl aes-256-cbc -K $encrypted_1b0fd0215972_key -iv $encrypted_1b0fd0215972_iv -in secret.zip.enc -out secret.zip -d
- unzip secret.zip

script:
- sudo cp deploy/21-prepare.conf /etc/rsyslog.d/
- sudo /etc/init.d/rsyslog restart
- sudo bash configure-linux.sh -a nicosmaris -t $(cat loggly_token) -u nicos -p $(cat loggly_password)
- exec > /tmp/travis.log 2>&1
- sed -i "s/logglytoken/$(cat loggly_token)/" deploy/install_docker.sh
- sed -i "s/logglypassword/$(cat loggly_password)/" deploy/install_docker.sh
- pip install -r requirements.txt
- behave features/mandatory.feature
- python provision.py input.yml

